import { createHash } from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { acquirePrivateLock, publishPrivateFile } from '../../../project/durable-state.mjs'
import { checkManagedRoots } from '../../../project/file-class.mjs'
import { atomicReplacePrivateText, ensureContainedPrivateDirectory, openRegularFileNoFollow, readRegularTextNoFollow, realPathAsStored } from '../../../project/private-state.mjs'

// Private per-workspace state for one Obsidian view:
//
//   <workspaceRoot>/vaults/<scopeId>/                 the editable vault, unless it was allocated elsewhere or a vaultRoot is named
//   <workspaceRoot>/state/allocations/<scopeId>.json  where the view's vault was allocated, when it was (see below)
//   <workspaceRoot>/state/manifests/<scopeId>/        trusted manifests and the current pointer
//   <workspaceRoot>/state/journals/<scopeId>/<id>/    publication journals
//   <workspaceRoot>/recovery/objects/<sha256>.bin     immutable content-addressed bytes
//   <workspaceRoot>/recovery/<journalId>/<unit>/      displaced files, receipts, and the unit's exchange candidate
//   <workspaceRoot>/recovery/.exchange-probe/         scratch files of the exchange self-test, nothing else
//   <workspaceRoot>/staging/<journalId>/              disposable generated bytes that no exchange ever names
//   <vault>/.atelier-publication/                     the vault lock, shared by every view of the vault
//
// Immutable records are published with publishPrivateFile: a complete file
// appears atomically under a name that is never overwritten. What that gives
// is an all-or-nothing record that survives a process crash; it is fsynced,
// which on some platforms is weaker than a full device flush. A displaced
// file is different: it is the very file that occupied a note path, it is
// moved and never copied over, and a program that still holds it open may
// write into it later. It is therefore never treated as immutable; its digest
// at the time of the move is recorded in a receipt and re-checked.
//
// A candidate that replaces an existing file is exchanged with it, so after
// the exchange the candidate's path holds the displaced bytes. That path is
// therefore in the unit's recovery directory, never in staging: staging is
// discardable, and displaced bytes must not sit in a discardable area for an
// instant. The candidate is written and fsynced in staging, where it is only
// generated bytes, named with its digest by the journal, and only then moved
// to its exchange path. What a file at an exchange path is, is decided from
// the journal: bytes with the recorded candidate digest are generated and
// ours; anything else is somebody's bytes and is kept. The candidate names
// end in `.candidate`; everything else the store puts in a unit directory
// ends in `.bin` or `.json`, so the names cannot collide.

export const EXCHANGE_CANDIDATE_NAME = 'exchange.candidate'
export const LATE_EXCHANGE_CANDIDATE_NAME = 'exchange.late.candidate'

export const VAULT_LOCK_DIRECTORY = '.atelier-publication'

// The vault lock, with the semantics of every private lock: the newest ticket
// owns it, a release marker frees it, and a ticket whose process is gone on
// this host is stale and is taken over. Nothing else is ever written here.
// Tickets of superseded generations are removed while the lock is held, the
// marker before its ticket, so the directory does not grow inside a person's
// vault and an interrupted removal never leaves a marker without its ticket.
export function acquireVaultLock(store) {
  const directory = ensureContainedPrivateDirectory({ workspaceRoot: store.vaultRoot, directory: path.dirname(store.vaultLockPath), label: 'vault publication lock' })
  const release = acquirePrivateLock(path.join(directory, path.basename(store.vaultLockPath)))
  try {
    const owners = `${store.vaultLockPath}.owners`
    const names = fs.readdirSync(owners).filter((name) => /^\d{12}\.(json|released)$/.test(name)).sort()
    const newest = names.filter((name) => name.endsWith('.json')).at(-1)?.slice(0, 12)
    for (const name of names.filter((item) => item.slice(0, 12) < newest).sort((left, right) => (left.endsWith('.released') ? -1 : 1) - (right.endsWith('.released') ? -1 : 1))) {
      fs.rmSync(path.join(owners, name), { force: true })
    }
  } catch { /* history that cannot be pruned is harmless */ }
  return release
}

const IDENTIFIER = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/
const DIGEST = /^sha256:[0-9a-f]{64}$/

export const sha256Digest = (bytes) => `sha256:${createHash('sha256').update(bytes).digest('hex')}`

export class PublicationRefusal extends Error {
  constructor(code, message, detail = {}) {
    super(`${code}: ${message}`)
    this.name = 'PublicationRefusal'
    this.code = code
    this.detail = detail
  }
}

export function refuse(code, message, detail) {
  throw new PublicationRefusal(code, message, detail)
}

// Identifiers become directory names. ':' is legal in an identifier and is not
// legal in a file name everywhere.
const segment = (identifier) => identifier.replaceAll(':', '_')

export function readFileDigest(file) {
  let descriptor
  try {
    descriptor = openRegularFileNoFollow(file)
  } catch (error) {
    if (error.code === 'ENOENT') return null
    throw error
  }
  try { return sha256Digest(fs.readFileSync(descriptor)) } finally { fs.closeSync(descriptor) }
}

export function readFileBytes(file) {
  const descriptor = openRegularFileNoFollow(file)
  try { return fs.readFileSync(descriptor) } finally { fs.closeSync(descriptor) }
}

function publishOnce(file, bytes) {
  try {
    publishPrivateFile(file, bytes)
  } catch (error) {
    // The name is taken by different bytes. An immutable record is never replaced.
    if (error.code !== 'EEXIST') throw error
    return false
  }
  return true
}

// ---------------------------------------------------------------------------
// Where a view's vault is
// ---------------------------------------------------------------------------

// A view of a workspace that decided where its vaults live gets a folder
// there, allocated once at its first publication (by the maintenance engine)
// and recorded, owner only, in the workspace's private state:
//
//   <workspaceRoot>/state/allocations/<scopeId>.json   atelier-obsidian-vault-allocation/v1
//
// A view without a record has its vault where every earlier release put it,
// `<workspaceRoot>/vaults/<scopeId>`: a vault published there stays there
// until it is moved, and a workspace that decided no place publishes there as
// before. The record is the one thing that names another folder, and the
// store reads it, so every reader of a view's vault (the engine, source apply,
// the proposal adapter, `open`) finds the same one.

export const VAULT_ALLOCATION_SCHEMA = 'atelier-obsidian-vault-allocation/v1'
export const VAULT_ORIGINS = Object.freeze(['allocated', 'legacy-data-root'])

const TIMESTAMP = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?Z$/
const CONTROL = /[\u0000-\u001f\u007f]/
// `device` and `inode` name the folder that was made, as decimal strings (a 64-bit number does not fit a JSON number):
// a folder at the recorded path that is another one (restored, moved in, made again by someone else) is never
// published into.
const ALLOCATION_KEYS = Object.freeze(['schema', 'workspaceId', 'scopeId', 'path', 'name', 'parent', 'device', 'inode', 'allocatedAt'])
const DECIMAL = /^(0|[1-9][0-9]{0,19})$/
const isPlainPath = (value) => typeof value === 'string' && value.length <= 4096 && !CONTROL.test(value) && path.isAbsolute(value) && path.resolve(value) === value

export const allocationFile = (workspaceRoot, scopeId) => path.join(workspaceRoot, 'state', 'allocations', `${segment(scopeId)}.json`)
export const legacyVaultRoot = (workspaceRoot, scopeId) => path.join(workspaceRoot, 'vaults', segment(scopeId))

export function validateVaultAllocation(document, { workspaceId, scopeId }) {
  const code = 'invalid-vault-allocation'
  if (document === null || typeof document !== 'object' || Array.isArray(document)) refuse(code, 'a vault allocation is an object')
  const unknown = Object.keys(document).filter((key) => !ALLOCATION_KEYS.includes(key))
  if (unknown.length > 0 || ALLOCATION_KEYS.some((key) => !Object.hasOwn(document, key))) refuse(code, 'a vault allocation carries exactly its own members', { unknown: unknown.sort() })
  if (document.schema !== VAULT_ALLOCATION_SCHEMA) refuse(code, 'a vault allocation names an unknown schema')
  if (document.workspaceId !== workspaceId || document.scopeId !== scopeId || !IDENTIFIER.test(String(scopeId))) refuse(code, 'the vault allocation belongs to another workspace or view')
  if (!isPlainPath(document.path) || !isPlainPath(document.parent)) refuse(code, 'the vault allocation names a folder that is not an absolute, plainly written path')
  if (path.dirname(document.path) !== document.parent || path.basename(document.path) !== document.name) refuse(code, 'the vault allocation names its folder inconsistently')
  if (typeof document.device !== 'string' || !DECIMAL.test(document.device) || typeof document.inode !== 'string' || !DECIMAL.test(document.inode)) refuse(code, 'the vault allocation names its folder\'s device and inode as decimal strings')
  if (typeof document.allocatedAt !== 'string' || !TIMESTAMP.test(document.allocatedAt)) refuse(code, 'the vault allocation needs a UTC time')
  return document
}

// The record of a view, validated, or null when it has none. Reads only.
export function readVaultAllocation({ workspaceRoot, workspaceId, scopeId }) {
  let text
  try { text = readRegularTextNoFollow(allocationFile(workspaceRoot, scopeId)) } catch (error) {
    if (error.code === 'ENOENT') return null
    return refuse('invalid-vault-allocation', 'the vault allocation cannot be read', { cause: error.code ?? String(error.message) })
  }
  let document
  try { document = JSON.parse(text) } catch { return refuse('invalid-vault-allocation', 'the vault allocation is not JSON') }
  return validateVaultAllocation(document, { workspaceId, scopeId })
}

// The device and inode of a folder, as an allocation records them; null when nothing is there.
export function folderIdentity(folder) {
  const stat = fs.lstatSync(folder, { bigint: true, throwIfNoEntry: false })
  return stat === undefined ? null : { device: String(stat.dev), inode: String(stat.ino), directory: stat.isDirectory(), link: stat.isSymbolicLink() }
}

// Whether the folder at an allocation's path is the one it recorded: 'same', 'missing', or 'replaced'.
export function allocatedFolderState(allocation) {
  const found = folderIdentity(allocation.path)
  if (found === null) return 'missing'
  return found.directory && !found.link && found.device === allocation.device && found.inode === allocation.inode ? 'same' : 'replaced'
}

// Written only by the maintenance engine, under its lock, and by what moves a vault under the same lock.
export function writeVaultAllocation({ workspaceRoot, allocation }) {
  validateVaultAllocation(allocation, allocation)
  const directory = ensureContainedPrivateDirectory({ workspaceRoot, directory: path.dirname(allocationFile(workspaceRoot, allocation.scopeId)), label: 'Obsidian vault allocations' })
  atomicReplacePrivateText(path.join(directory, path.basename(allocationFile(workspaceRoot, allocation.scopeId))), `${JSON.stringify(allocation, null, 2)}\n`)
  return allocation
}

// Where a view's vault is, without creating anything: { path, origin, allocation }.
export function vaultRootFor({ workspaceRoot, workspaceId, scopeId }) {
  const allocation = readVaultAllocation({ workspaceRoot, workspaceId, scopeId })
  return allocation === null
    ? { path: legacyVaultRoot(workspaceRoot, scopeId), origin: 'legacy-data-root', allocation: null }
    : { path: allocation.path, origin: 'allocated', allocation }
}

// Whether a view has a committed generation, whichever folder it was published into.
export const hasCommittedGeneration = ({ workspaceRoot, scopeId }) => fs.existsSync(path.join(workspaceRoot, 'state', 'manifests', segment(scopeId), 'current.json'))

// `repositoryRoots` is required: every enrolled repository root of the loaded
// project. Neither the workspace state nor the vault may overlap one of them,
// in either direction, lexically or by real path; the store refuses before it
// creates anything. A caller with no enrolled repository (a test in a
// temporary directory) says so with an explicit empty list.
//
// Without `vaultRoot` the vault is where the view's allocation says, else in
// the workspace's `vaults/` (vaultRootFor). An allocated folder must be the
// very folder the record names (device and inode): one that has gone is made
// again by the maintenance engine under its lock (ensureVaultAllocation), and
// until then, like one that another folder replaced, the store refuses.
export function createRecoveryStore({ workspaceRoot, workspaceId, scopeId, vaultRoot, repositoryRoots } = {}) {
  if (typeof workspaceRoot !== 'string' || !path.isAbsolute(workspaceRoot)) throw new TypeError('workspaceRoot must be an absolute path')
  for (const [label, value] of [['workspaceId', workspaceId], ['scopeId', scopeId]]) {
    if (typeof value !== 'string' || !IDENTIFIER.test(value)) throw new TypeError(`${label} must be a contract identifier`)
  }
  if (!Array.isArray(repositoryRoots) || repositoryRoots.some((item) => typeof item !== 'string' || !path.isAbsolute(item))) {
    throw new TypeError('repositoryRoots must list the absolute root of every enrolled repository; pass an explicit empty list when there is none')
  }
  if (vaultRoot !== undefined && (typeof vaultRoot !== 'string' || !path.isAbsolute(vaultRoot))) throw new TypeError('vaultRoot must be an absolute path')
  const allocation = vaultRoot === undefined ? readVaultAllocation({ workspaceRoot, workspaceId, scopeId }) : null
  const namedVault = vaultRoot ?? allocation?.path
  const guard = checkManagedRoots({ managedRoots: [workspaceRoot, ...(namedVault === undefined ? [] : [namedVault])], repositoryRoots })
  if (!guard.ok) refuse(guard.refusals[0].code, guard.refusals[0].message, { refusals: guard.refusals })
  if (allocation !== null) {
    const found = allocatedFolderState(allocation)
    if (found === 'missing') refuse('vault-allocation-missing', 'the folder allocated to this view is gone; the maintenance service makes it again at its next tick', { path: allocation.path })
    if (found === 'replaced') refuse('vault-allocation-replaced', 'another folder is where this view\'s vault was allocated; Atelier publishes only into the folder it made', { path: allocation.path })
  }
  fs.mkdirSync(workspaceRoot, { recursive: true, mode: 0o700 })
  // Both as the file system stores them: the vault root is what the app is told, and what it compares its own
  // working-directory spelling with.
  const root = realPathAsStored(workspaceRoot)
  const privateDir = (...parts) => ensureContainedPrivateDirectory({ workspaceRoot: root, directory: path.join(root, ...parts), label: 'Obsidian publication state' })
  const requestedVault = namedVault ?? legacyVaultRoot(root, scopeId)
  // A vault this store places itself, under the data root or where the view's vault was allocated, is private to this
  // user from the start: it will hold the plugin's bearer.
  fs.mkdirSync(requestedVault, { recursive: true, ...(vaultRoot === undefined ? { mode: 0o700 } : {}) })
  const vault = realPathAsStored(requestedVault)
  const inside = (parent, child) => { const relative = path.relative(parent, child); return relative === '' || (!relative.startsWith('..') && !path.isAbsolute(relative)) }
  for (const area of ['state', 'recovery', 'staging']) {
    if (inside(path.join(root, area), vault) || inside(vault, path.join(root, area))) refuse('vault-overlaps-private-state', 'the vault may not overlap private publication state')
  }
  const manifests = privateDir('state', 'manifests', segment(scopeId))
  const journals = privateDir('state', 'journals', segment(scopeId))
  const locks = privateDir('state', 'locks')
  const objects = privateDir('recovery', 'objects')
  const staging = privateDir('staging')
  const pointerFile = path.join(manifests, 'current.json')

  const store = {
    workspaceRoot: root,
    workspaceId,
    scopeId,
    vaultRoot: vault,
    // Placed by this store under the workspace state or where the view's vault was allocated, rather than named by the
    // caller, and really there: a vault path that is a link leads to a folder someone else chose, which is only looked
    // at and never receives the bearer.
    managedVaultRoot: vaultRoot === undefined && vault === requestedVault,
    linkedVaultRoot: vaultRoot === undefined && vault !== requestedVault,
    // Where the vault is and why: named by the caller, allocated for the view, or under the data root.
    vaultOrigin: vaultRoot !== undefined ? 'explicit' : allocation === null ? 'legacy-data-root' : 'allocated',
    allocation,
    journalsRoot: journals,
    lockPath: path.join(locks, `${segment(scopeId)}.lock`),
    // One publisher per vault, whichever view or workspace state it belongs to.
    // Two stores share nothing but the vault, so this lock lives under the
    // vault's real path, in a dot-directory no note path can name.
    vaultLockPath: path.join(vault, VAULT_LOCK_DIRECTORY, 'vault.lock'),
    ref: (absolute) => path.relative(root, absolute).split(path.sep).join('/'),
    resolve(ref) {
      const absolute = path.resolve(root, ref)
      if (!inside(root, absolute) || absolute === root) throw new TypeError('a store reference must stay inside the workspace state')
      return absolute
    },
    journalDir: (journalId) => privateDir('state', 'journals', segment(scopeId), segment(journalId)),
    stagingDir: (journalId) => privateDir('staging', segment(journalId)),
    stagingRoot: staging,
    // Where the exchange self-test runs: inside recovery, because that is where exchange candidates live.
    exchangeProbeDir: () => privateDir('recovery', '.exchange-probe'),
    // Generated bytes on their way to a path: written here, and for a created file linked from here.
    preparedPath: (journalId, unit, { late = false } = {}) => path.join(store.stagingDir(journalId), `${String(unit).padStart(6, '0')}${late ? '.late' : ''}.candidate`),
    // The path handed to the exchange. Computed without creating anything; unitDir creates the directory.
    exchangeCandidatePath: (journalId, unit, { late = false } = {}) => path.join(root, 'recovery', segment(journalId), String(unit).padStart(6, '0'), late ? LATE_EXCHANGE_CANDIDATE_NAME : EXCHANGE_CANDIDATE_NAME),
    unitsRoot: (journalId) => path.join(root, 'recovery', segment(journalId)),
    unitDir: (journalId, unit) => privateDir('recovery', segment(journalId), String(unit).padStart(6, '0')),
    displacedPath: (journalId, unit, name = 'displaced.bin') => path.join(store.unitDir(journalId, unit), name),

    // Immutable, content-addressed bytes (a base, an observed edit, an outside writer's bytes).
    retainObject(bytes) {
      const digest = sha256Digest(bytes)
      const file = path.join(objects, `${digest.slice('sha256:'.length)}.bin`)
      publishPrivateFile(file, bytes)
      return { digest, ref: store.ref(file) }
    },
    readObject(digest) {
      if (!DIGEST.test(digest)) throw new TypeError('digest required')
      const bytes = readFileBytes(path.join(objects, `${digest.slice('sha256:'.length)}.bin`))
      if (sha256Digest(bytes) !== digest) refuse('recovery-object-corrupt', 'a retained object no longer matches its name')
      return bytes
    },
    writeReceipt(journalId, unit, receipt) {
      const body = Buffer.from(`${JSON.stringify({ schema: 'atelier-obsidian-recovery-receipt/v1', journalId, unit, ...receipt }, null, 2)}\n`, 'utf8')
      const file = path.join(store.unitDir(journalId, unit), `receipt-${receipt.role}-${sha256Digest(body).slice(7, 19)}.json`)
      publishOnce(file, body)
      return store.ref(file)
    },
    listReceipts(journalId) {
      const base = path.join(root, 'recovery', segment(journalId))
      if (!fs.existsSync(base)) return []
      const receipts = []
      for (const unit of fs.readdirSync(base).sort()) {
        for (const name of fs.readdirSync(path.join(base, unit)).filter((entry) => /^receipt-.*\.json$/.test(entry)).sort()) {
          receipts.push(JSON.parse(readRegularTextNoFollow(path.join(base, unit, name))))
        }
      }
      return receipts
    },

    // Trusted manifest. The manifest file is immutable; only the small pointer
    // is replaced, and only as the last step of a publication.
    readCurrent() {
      let text
      try { text = readRegularTextNoFollow(pointerFile) } catch (error) { if (error.code === 'ENOENT') return null; throw error }
      const pointer = JSON.parse(text)
      if (pointer.scopeId !== scopeId || pointer.workspaceId !== workspaceId) refuse('state-mismatch', 'the manifest pointer belongs to another view')
      return pointer
    },
    readCurrentManifest() {
      const pointer = store.readCurrent()
      if (!pointer) return null
      const bytes = readFileBytes(path.join(manifests, pointer.manifestFile))
      if (sha256Digest(bytes) !== pointer.manifestDigest) refuse('state-mismatch', 'the trusted manifest no longer matches its pointer')
      return JSON.parse(bytes.toString('utf8'))
    },
    commitManifest({ manifestBytes, generationId, journalId, retained = [], committedAt }) {
      const manifestDigest = sha256Digest(manifestBytes)
      const manifestFile = `${segment(generationId)}--${manifestDigest.slice(7, 19)}.json`
      publishPrivateFile(path.join(manifests, manifestFile), manifestBytes)
      const pointer = { schema: 'atelier-obsidian-current-manifest/v1', workspaceId, scopeId, generationId, manifestFile, manifestDigest, journalId, committedAt, retained }
      atomicReplacePrivateText(pointerFile, `${JSON.stringify(pointer, null, 2)}\n`)
      return pointer
    },
  }
  return store
}
