export function renderReviewPage() {
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Review workspace</title>
<style>body{font:18px/1.6 system-ui;max-width:850px;margin:3rem auto;padding:0 1.5rem;color:#202524;background:#faf9f5}h1,h2{line-height:1.2}label{display:block;margin-top:1rem}input,textarea,select,button{font:inherit;padding:.5rem;max-width:100%;box-sizing:border-box}textarea{width:100%;min-height:7rem}button{cursor:pointer;margin:.5rem .5rem .5rem 0}button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:3px solid #1c695c;outline-offset:3px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#eee;padding:1rem}article{border-top:1px solid #b8b8af;padding:1rem 0}.note{color:#49534e}#status{position:sticky;top:0;background:#faf9f5;padding:.5rem;border-bottom:1px solid #aaa}</style>
<h1>Review workspace</h1><p class="note">Questions and corrections stay yours. Decisions record local judgment; source changes require a separate owner action.</p>
<p id="status" role="status" aria-live="polite">Ready to open a document or a run.</p>
<label>Your name <input id="reviewer" autocomplete="name"></label><p class="note">Recorded as locally asserted identity.</p>
<h2>Read and respond</h2><form id="open-document"><label>Repository <input id="repo" required></label><label>Document path <input id="path" required placeholder="README.md"></label><button>Open document</button></form>
<pre id="document" tabindex="0" aria-label="Source document"></pre>
<label>Passage (copy its exact wording)<textarea id="anchor"></textarea></label>
<label>Response type<select id="response-type"><option value="question">Question</option><option value="correction">Correction</option><option value="discussion">Discuss</option></select></label>
<label>Your response<textarea id="wording"></textarea></label><button id="save-response">Save response</button><button id="save-position">Save reading position</button>
<h2>Review a run</h2><form id="open-run"><label>Run ID <input id="run-id" required></label><button>Open run</button></form><div id="run"></div>
<h2>Recorded contributions</h2><p>Viewing a document does not record agreement. Old responses remain attached to their original revision.</p><div id="history"></div>
<script type="module">
const el=id=>document.getElementById(id);let nonce='',doc=null,run=null,history=[],pending=null,responseTarget='response-'+crypto.randomUUID();
const drafts=new Map();
const status=message=>el('status').textContent=message;
async function request(url,body){if(!url.startsWith('/api/review/'))throw new Error('Invalid local route');
const options=body?{method:'POST',headers:{'Content-Type':'application/json','X-Atelier-Nonce':nonce},body:JSON.stringify(body)}:{};
const response=await fetch('/api/review/'+url.slice('/api/review/'.length),options);const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Request failed');return result}
async function auth(){nonce=(await request('/api/review/session',{})).mutationNonce}
function para(parent,text){const p=document.createElement('p');p.textContent=text;parent.append(p);return p}
async function refresh(){history=(await request('/api/review/records')).records;el('history').replaceChildren();for(const record of history){const a=document.createElement('article');para(a,record.input.kind+' · asserted by '+record.identity.name+' · '+record.recordedAt);para(a,record.input.wording||record.input.rationale||'Reading position saved');para(a,'Revision: '+(record.input.documentDigest||record.input.evidenceDigest));if(record.input.anchor)para(a,record.input.anchor);if(record.input.kind==='position'){const resume=document.createElement('button');resume.textContent='Resume '+record.input.repo+'/'+record.input.path;resume.onclick=()=>{el('repo').value=record.input.repo;el('path').value=record.input.path;el('open-document').requestSubmit()};a.append(resume)}if(record.input.kind==='decision'){para(a,'Decision: '+record.input.decision+' · claim '+record.input.targetId+' · version '+record.version);if(record.input.revision)para(a,'Proposed successor wording: '+record.input.revision);if(record.input.decision==='accepted'){const button=document.createElement('button');button.textContent='Inspect owner handoff';button.onclick=async()=>{try{const result=await request('/api/review/handoff?'+new URLSearchParams({id:record.input.requestId}));const pre=document.createElement('pre');pre.textContent=JSON.stringify(result,null,2);a.append(pre)}catch(error){status(error.message)}};a.append(button)}}el('history').append(a)}}
function version(kind,targetId,extra){return history.filter(r=>r.input.kind===kind&&r.input.targetId===targetId&&(r.input.runId||null)===(extra.runId||null)&&(r.input.repo||null)===(extra.repo||null)&&(r.input.path||null)===(extra.path||null)&&(kind!=='position'||r.input.reviewer===el('reviewer').value.trim())).length}
async function save(kind,targetId,extra){const input={kind,targetId,expectedVersion:version(kind,targetId,extra),reviewer:el('reviewer').value.trim(),...extra};const fingerprint=JSON.stringify(input);if(!pending||pending.fingerprint!==fingerprint)pending={fingerprint,input:{...input,requestId:crypto.randomUUID()}};const attempt=pending;status('Saving…');try{await auth();await request('/api/review/contributions',attempt.input);if(pending===attempt)pending=null;status('Saved to local history.');await refresh().catch(()=>status('Saved; history refresh unavailable.'));return true}catch(error){const recovery=error.message.includes('stale contribution version')?'Reopen the run to inspect newer decisions before saving again.':error.message.includes('document changed')?'Reopen the document and explicitly select a passage in its new revision.':error.message.includes('claim evidence changed')?'Create a new run against current evidence before deciding.':'Retry with Save after the active writer or service is available.';status('Not confirmed saved: '+error.message+'. Your wording remains here. '+recovery)}}
el('open-document').onsubmit=async event=>{event.preventDefault();try{const repo=el('repo').value,path=el('path').value;const loaded=await request('/api/review/document?'+new URLSearchParams({repo,path}));doc={repo,path,...loaded};el('document').textContent=doc.text;await refresh();const positions=history.filter(r=>r.input.kind==='position'&&r.input.repo===repo&&r.input.path===path&&r.input.documentDigest===doc.digest&&r.input.reviewer===el('reviewer').value.trim());const last=positions.at(-1);if(last){el('anchor').value=last.input.anchor;const range=document.createRange();const node=el('document').firstChild;range.setStart(node,Math.min(last.input.position,node.length));range.collapse(true);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);el('document').focus();const rect=range.getBoundingClientRect();if(rect.height)window.scrollBy(0,rect.top-window.innerHeight/3)}status('Document opened. Previous contributions are listed below.')}catch(error){status(error.message)}};
el('save-response').onclick=async()=>{if(!doc)return status('Open a document first.');if(await save('response',responseTarget,{repo:doc.repo,path:doc.path,documentDigest:doc.digest,anchor:el('anchor').value,responseType:el('response-type').value,wording:el('wording').value})){el('wording').value='';responseTarget='response-'+crypto.randomUUID()}};
el('save-position').onclick=()=>{if(!doc)return status('Open a document first.');const anchor=el('anchor').value;return save('position','reading-position',{repo:doc.repo,path:doc.path,documentDigest:doc.digest,anchor,position:Math.max(0,doc.text.indexOf(anchor))})};
el('open-run').onsubmit=async event=>{event.preventDefault();try{run=await request('/api/review/run?'+new URLSearchParams({id:el('run-id').value}));await refresh();el('run').replaceChildren();para(el('run'),'Answer completeness: '+run.run.score+'%. This is not evidence confidence or runtime readiness.');para(el('run'),run.current?'Evidence currently matches.':'Historical evidence: current acceptance unavailable.');for(const [index,claim] of run.run.claims.entries()){const a=document.createElement('article');para(a,claim.subject+' — '+claim.predicate+' — '+claim.object);para(a,'Claim ID: '+claim.claimId);para(a,claim.notes.join(' '));const mapped=run.snapshot.claimEvidence[index];para(a,'Mapped evidence: '+mapped.status);for(const source of mapped.resolved){para(a,source.id+' · '+source.repo+'/'+source.path);para(a,source.excerpt)}if(mapped.unresolved.length)para(a,'Unresolved references: '+mapped.unresolved.join(', '));para(a,'Evidence: operator answers and the recorded source inventory. Source presence alone does not substantiate this relationship.');const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Inspect recorded inputs and source identities';details.append(summary);const pre=document.createElement('pre');pre.textContent=JSON.stringify({mapping:mapped,answers:run.snapshot.answers,sources:run.snapshot.sources,limitations:run.snapshot.limitations},null,2);details.append(pre);a.append(details);para(a,'Acceptance records your judgment and prepares an owner handoff. It does not apply, publish or promote the claim.');const label=document.createElement('label');label.textContent='Reason or proposed revision';const reason=document.createElement('textarea');const draftKey=run.run.runId+':'+claim.claimId;reason.value=drafts.get(draftKey)||'';reason.oninput=()=>drafts.set(draftKey,reason.value);label.append(reason);a.append(label);for(const decision of ['accepted','rejected','revised']){const button=document.createElement('button');button.textContent={accepted:'Accept',rejected:'Reject',revised:'Propose revision'}[decision];button.disabled=!run.current||(decision==='accepted'&&(mapped.status!=='linked-source'||run.run.blockers.length>0));button.onclick=()=>save('decision',claim.claimId,{runId:run.run.runId,evidenceDigest:run.snapshot.digest,decision,rationale:reason.value,...(decision==='revised'?{revision:reason.value}:{})});a.append(button)}el('run').append(a)}}catch(error){status(error.message)}};
refresh().catch(error=>status('History unavailable: '+error.message));
</script></html>`
}
