import { createCooperativeBudget, isSchedulingStop } from '../materialize/prepare-view.mjs'
import fs from 'node:fs'
import fsp from 'node:fs/promises'
import path from 'node:path'
import { setTimeout as sleep } from 'node:timers/promises'
import { acquirePrivateLock, publishPrivateFile, syncPrivateDirectory } from '../../../project/durable-state.mjs'
import { OBSIDIAN_EXT_KEY, ObsidianContractRefusal, assertObsidianContract, manifestLayoutVersion } from '../contracts.mjs'
import { isPluginOwnedPath, isPolicySettingsPath, isUserOwnedSettingsPath, preparePolicySettingsFile } from '../materialize/settings.mjs'
import { PLUGIN_DATA_MODE, PLUGIN_DATA_PATH, PLUGIN_SOURCE_MODE } from '../plugin-bridge/channel.mjs'
import { createJournal, newJournalId } from '../recovery/journal.mjs'
import { recheckDisplacedFiles } from '../recovery/late-writer.mjs'
import { publishedSinceCommit, reconcileUnit, recordDisplaced, recoverPublicationsLocked, retireStagedFile } from '../recovery/restart.mjs'
import { PublicationRefusal, acquireVaultLock, allocatedFolderState, readFileBytes, readFileDigest, refuse, sha256Digest } from '../recovery/store.mjs'
import { PROTOCOL_ID, isAddressableVaultPath } from './bridge-script.mjs'
import { probeExchange } from './exchange.mjs'
import { CRASH_INJECTION_TEST_SEAM } from './test-seam.mjs'
import { createDirectAdapter } from './transport.mjs'

// publishView: conditional publication of one prepared view into an editable
// vault. The order is the contract's:
//
//   recover interrupted publications -> write every candidate in staging
//   (same volume, fsync), store the manifest, open the journal, which names
//   every candidate path and digest, and move each candidate that will be
//   exchanged into its unit's recovery directory -> per note: retain the comparison baseline,
//   write the capture entry, publish conditionally, verify bytes -> re-check
//   displaced files after a quiet period -> commit the trusted manifest last.
//
// Until the manifest is committed the view is `updating`. A refusal for one
// note does not stop the others; a refused note stays one generation behind
// and the view converges on a later run. No editable path is ever replaced
// unconditionally: an existing file changes only through the atomic exchange
// inside the critical section, a new file appears only through an exclusive
// link, and a file leaves only by being moved to recovery.
//
// Where candidates are: an exchange leaves the displaced bytes at the
// candidate's path, so a candidate that replaces an existing file is exchanged
// from `recovery/<journalId>/<unit>/`, never from staging. Staging holds only
// generated bytes that no exchange names: every candidate while it is written,
// and the candidates of created files until they are linked into the vault.
//
// Atelier's own plugin files (kind `plugin`) go through the same units, with
// two differences: each is compared with what the disk holds when the run
// begins rather than with an earlier generation, so whatever is there is
// displaced to recovery and never lost, and a plugin path that a person has to
// repair never holds the view back. The plugin's data file names a bearer and
// is written only into a vault root that is private to this user.
//
// First publication into a vault no Obsidian lists (`direct-unheld`). A running
// or unknowable app that cannot be coordinated with still refuses the whole
// publication, as ever, except in one case: the view has never been committed,
// its vault is the folder Atelier allocated for it (the record's device and
// inode), and the evidence (`unheldEvidence`, read by the caller from the app's
// own settings file) says no list this account's Obsidian keeps names that
// folder, a folder above it or one inside it, on macOS or Linux. The vault is
// then filled in this process, with no editor, by creating files only: every
// file appears through the exclusive link, where nothing is, or not at all. A
// unit that would replace or remove a file, or write a settings file over one
// that is there, refuses as `editor-uncoordinated` (blocking) and writes
// nothing. No editor can hold an unsaved buffer of a file that does not exist,
// so nothing a person wrote can be lost, whoever holds the vault. The evidence
// is read again immediately before the first unit and whenever two seconds
// have passed since the last reading; once a reading gives no evidence, every
// remaining unit refuses and nothing is committed. A run that completes is
// committed before `open` tells the app about the vault; a run that stops
// partway reports why, and what it left is published through the app.

const hex = (digest) => digest.slice('sha256:'.length)
const iso = (clock) => { const value = clock(); return (value instanceof Date ? value : new Date(value)).toISOString() }
const REFUSED_BY_EDIT = new Set(['editor-edit', 'disk-changed'])
const unreleased = new Map()
// A release kept earlier whose lock folder is gone when it is tried again (the vault deleted, replaced, or made again
// empty at its path) holds nothing there, and is dropped rather than holding every later publication of that vault back.
// A vault put back holds its ticket again, and the release kept for it then succeeds.
const lockFolderGone = (error) => error?.code === 'ENOENT' || error?.code === 'ENOTDIR'

// A note another program replaces by rename can change between the check of its leaf and the open
// (ELEAFCHANGED). Every rename leaves a complete file, so it is read again; one that keeps changing is left to
// publishView, which reports it for that unit only.
const READ_ATTEMPTS = 5
function readNote(file) {
  for (let attempt = 1; ; attempt += 1) {
    try { return readFileBytes(file) } catch (error) {
      if (error.code === 'ENOENT') return null
      if (error.code !== 'ELEAFCHANGED' || attempt >= READ_ATTEMPTS) throw error
    }
  }
}

function validatePreparedView(preparedView, store) {
  if (!preparedView || !Array.isArray(preparedView.files) || !preparedView.manifest) throw new TypeError('publishView needs a prepared view')
  try { assertObsidianContract('generation-manifest', preparedView.manifest) } catch (error) {
    if (error instanceof ObsidianContractRefusal) refuse('invalid-prepared-view', 'the prepared manifest does not satisfy its contract', error.detail)
    throw error
  }
  const { manifest } = preparedView
  if (manifest.scopeId !== store.scopeId) refuse('invalid-prepared-view', 'the prepared view belongs to another scope')
  if (manifest.completeness.status !== 'complete') refuse('invalid-prepared-view', 'a partial generation is not published')
  // Closed over the manifest itself: one path names one file, as a note or as an attachment, once.
  const expected = new Map()
  for (const [declared, fileDigest] of [...manifest.notes.map((note) => [note.path, note.noteDigest]), ...manifest.attachments.map((item) => [item.path, item.digest])]) {
    if (expected.has(declared)) refuse('invalid-prepared-view', 'the manifest declares one path more than once')
    expected.set(declared, fileDigest)
  }
  // Atelier's plugin files are pinned by the settings unit's record in the manifest.
  const pinnedPlugin = manifest.ext?.[OBSIDIAN_EXT_KEY]?.settings?.pluginOwned?.files
  const pinned = new Map(Array.isArray(pinnedPlugin) ? pinnedPlugin.map((file) => [file?.path, file?.digest]) : [])
  const seen = new Set()
  for (const file of preparedView.files) {
    if (!isAddressableVaultPath(file.path) || isUserOwnedSettingsPath(file.path)) refuse('invalid-prepared-view', 'a prepared path is outside what the publisher may write')
    if (seen.has(file.path)) refuse('invalid-prepared-view', 'a prepared path appears twice')
    seen.add(file.path)
    if (file.kind === 'settings') {
      if (!isPolicySettingsPath(file.path)) refuse('invalid-prepared-view', 'only a policy settings file may be prepared as settings')
      continue
    }
    if (file.kind === 'plugin') {
      if (!isPluginOwnedPath(file.path) || !Buffer.isBuffer(file.bytes) || sha256Digest(file.bytes) !== file.digest || pinned.get(file.path) !== file.digest) {
        refuse('invalid-prepared-view', 'a plugin file, its digest and the digest the manifest pins disagree')
      }
      // Read by the app, never run by anyone: the data file owner-only, the others readable.
      if (file.mode !== (file.path === PLUGIN_DATA_PATH ? PLUGIN_DATA_MODE : PLUGIN_SOURCE_MODE)) refuse('invalid-prepared-view', 'a plugin file has a mode Atelier never gives one')
      pinned.delete(file.path)
      continue
    }
    if (!['note', 'attachment'].includes(file.kind) || isPolicySettingsPath(file.path) || isPluginOwnedPath(file.path)) refuse('invalid-prepared-view', 'a prepared file has an unknown kind')
    if (!Buffer.isBuffer(file.bytes) || sha256Digest(file.bytes) !== file.digest || expected.get(file.path) !== file.digest) {
      refuse('invalid-prepared-view', 'prepared bytes, their digest and the manifest disagree')
    }
    expected.delete(file.path)
  }
  if (expected.size > 0) refuse('invalid-prepared-view', 'the manifest names a file the prepared view does not carry')
  if (pinned.size > 0) refuse('invalid-prepared-view', 'the manifest pins a plugin file the prepared view does not carry')
  let parsedBytes = null
  if (Buffer.isBuffer(preparedView.manifestBytes)) {
    try { parsedBytes = JSON.parse(preparedView.manifestBytes.toString('utf8')) } catch { refuse('invalid-prepared-view', 'manifest bytes are not JSON') }
  }
  const manifestBytes = parsedBytes !== null && JSON.stringify(parsedBytes) === JSON.stringify(manifest)
    ? preparedView.manifestBytes
    : Buffer.from(`${JSON.stringify(manifest, null, 2)}\n`, 'utf8')
  return { manifest, manifestBytes }
}

// Every directory on the way to a vault path is a real directory. Missing
// ones are created; nothing existing is changed.
function ensureParents(vaultRoot, relativePath) {
  let current = vaultRoot
  for (const part of relativePath.split('/').slice(0, -1)) {
    current = path.join(current, part)
    let stat = fs.lstatSync(current, { throwIfNoEntry: false })
    if (!stat) {
      try { fs.mkdirSync(current) } catch (error) { if (error.code !== 'EEXIST') throw error }
      stat = fs.lstatSync(current)
    }
    if (stat.isSymbolicLink() || !stat.isDirectory()) return false
  }
  return true
}

// `created` receives the path once this call has created the file, and not before: cleanup removes only those.
function stageCandidate(file, bytes, mode, created = [], crash = () => {}) {
  const descriptor = fs.openSync(file, fs.constants.O_WRONLY | fs.constants.O_CREAT | fs.constants.O_EXCL, mode)
  created.push(file)
  try {
    crash('after-late-candidate-open')
    fs.writeFileSync(descriptor, bytes)
    fs.fchmodSync(descriptor, mode)
    fs.fsyncSync(descriptor)
  } finally {
    fs.closeSync(descriptor)
  }
  if (sha256Digest(readFileBytes(file)) !== sha256Digest(bytes)) throw Object.assign(new Error('staged bytes differ from the candidate'), { code: 'ESTAGE' })
}

// Keep units, compared ahead of the per-unit loop: each vault file is read
// and hashed once, several at a time through the thread pool, and a unit whose
// bytes are exactly the candidate's is settled as unchanged. Nothing else is
// decided here. A keep unit that is absent, holds other bytes, sits under an
// unsafe parent, is not a regular file or cannot be read goes through
// publishUnit as before, which reads it again. The checks are the ones the
// synchronous path makes (every parent a real directory, the leaf a regular
// file opened without following a link and bound to the file that was
// inspected); only the ordering and the concurrency differ, and a kept note
// is never written, so its comparison needs no place in the unit order.
const KEEP_COMPARISON_WIDTH = 16

async function unchangedKeepUnits(units, store) {
  const settled = new Set()
  const pending = units.filter((unit) => unit.op === 'keep')
  let next = 0
  const worker = async () => {
    while (next < pending.length) {
      const unit = pending[next]
      next += 1
      if (await holdsCandidateBytes(store.vaultRoot, unit.path, unit.candidateDigest)) settled.add(unit.path)
    }
  }
  await Promise.all(Array.from({ length: Math.min(KEEP_COMPARISON_WIDTH, pending.length) }, worker))
  return settled
}

async function holdsCandidateBytes(vaultRoot, relativePath, candidateDigest) {
  try {
    let current = vaultRoot
    for (const part of relativePath.split('/').slice(0, -1)) {
      current = path.join(current, part)
      const stat = await fsp.lstat(current)
      if (stat.isSymbolicLink() || !stat.isDirectory()) return false
    }
    const file = path.join(vaultRoot, relativePath)
    const before = await fsp.lstat(file)
    if (before.isSymbolicLink() || !before.isFile()) return false
    const handle = await fsp.open(file, fs.constants.O_RDONLY | (fs.constants.O_NOFOLLOW ?? 0))
    try {
      const opened = await handle.stat()
      if (!opened.isFile() || (before.ino !== 0 && (before.dev !== opened.dev || before.ino !== opened.ino))) return false
      return sha256Digest(await handle.readFile()) === candidateDigest
    } finally {
      await handle.close()
    }
  } catch {
    return false
  }
}

// The digest of what a vault path holds now: null when it is absent, sits
// under a parent that is not a real directory, is not a regular file or cannot
// be read. Only Atelier's plugin files are planned from it.
function currentDigestOf(vaultRoot, relativePath) {
  let current = vaultRoot
  for (const part of relativePath.split('/').slice(0, -1)) {
    current = path.join(current, part)
    const stat = fs.lstatSync(current, { throwIfNoEntry: false })
    if (!stat || stat.isSymbolicLink() || !stat.isDirectory()) return null
  }
  try { return readFileDigest(path.join(vaultRoot, relativePath)) } catch { return null }
}

// Whether publishing would only leave this plugin path for the person, as it
// stands: a parent that is a link or not a directory, a leaf that is not a
// regular file (path-unsafe), or the data file where the vault root cannot hold
// the bearer and is not one Atelier makes private itself (vault-not-private;
// see ensurePrivateVaultRoot). Read-only. Conservative: a leaf nobody may
// read, a parent that cannot be looked into, and a vault root Atelier keeps
// whose mode cannot be changed are left for the person too, but count here as
// a drift, as before.
function leftForThePerson(store, relativePath) {
  let current = store.vaultRoot
  for (const part of relativePath.split('/').slice(0, -1)) {
    current = path.join(current, part)
    const stat = fs.lstatSync(current, { throwIfNoEntry: false })
    if (!stat) break
    if (stat.isSymbolicLink() || !stat.isDirectory()) return true
  }
  const leaf = fs.lstatSync(path.join(store.vaultRoot, relativePath), { throwIfNoEntry: false })
  if (leaf && !leaf.isFile()) return true
  if (relativePath !== PLUGIN_DATA_PATH) return false
  if (store.linkedVaultRoot === true) return true
  const uid = typeof process.getuid === 'function' ? process.getuid() : null
  const root = fs.lstatSync(store.vaultRoot, { throwIfNoEntry: false })
  if (!root?.isDirectory() || uid === null || root.uid !== uid) return true
  return (root.mode & 0o077) !== 0 && store.managedVaultRoot !== true
}

// A generation that is already committed is published again, as it is, when a
// plugin file it carries is not on disk as it pins it: the person repaired a
// path Atelier had to leave, or removed or changed a file. The bytes are
// Atelier's and nothing else of the view changed, so the generation stays the
// same; its notes are kept, and its plugin units are planned from the disk as
// ever. A file prepared only where present that is gone is not a drift, and
// neither is one that publishing would only leave for the person again: it
// would change nothing, and it would need the app for nothing (a view that
// waits for an app for it would wait for a write that never comes).
function pluginFilesDrifted(preparedView, store) {
  return preparedView.files.some((file) => {
    if (file.kind !== 'plugin') return false
    const current = currentDigestOf(store.vaultRoot, file.path)
    if (current === file.digest || (current === null && file.onlyIfPresent === true)) return false
    try { return !leftForThePerson(store, file.path) } catch { return true }
  })
}

// One unit per file the publication creates, keeps, replaces or removes. Exported for the oracle tests.
export function planUnits({ files, priorManifest, pointer, ledger, pluginDisk = new Map() }) {
  const trusted = new Map()
  for (const note of priorManifest?.notes ?? []) trusted.set(note.path, note.noteDigest)
  for (const attachment of priorManifest?.attachments ?? []) trusted.set(attachment.path, attachment.digest)
  // A note kept because it was edited is still bound to the digest it was generated with.
  for (const item of pointer?.retained ?? []) if (item.priorDigest && !item.movedToRecovery) trusted.set(item.path, item.priorDigest)
  for (const [notePath, digest] of ledger) { if (digest === null) trusted.delete(notePath); else trusted.set(notePath, digest) }

  // A file leaves as an attachment when the prior generation listed it as one. Layout 1 kept every file under
  // `attachments/`, so there that folder says it too (of a file an interrupted run published); in layout 2 it is only
  // a repository's folder.
  const priorAttachments = new Set((priorManifest?.attachments ?? []).map((attachment) => attachment.path))
  const underAttachments = !priorManifest || manifestLayoutVersion(priorManifest) === 1
  const units = []
  const present = new Set()
  for (const file of files) {
    present.add(file.path)
    // A settings file prepared from the bytes it held when the view was prepared carries their digest: it is written only over them.
    if (file.kind === 'settings') { units.push({ path: file.path, kind: 'settings', op: 'settings', ...(Object.hasOwn(file, 'expectedDigest') ? { expectedDigest: file.expectedDigest } : {}) }); continue }
    if (file.kind === 'plugin') {
      const current = pluginDisk.get(file.path) ?? null
      // A plugin file the person removed while the plugin is off in this vault stays removed.
      if (current === null && file.onlyIfPresent === true) { units.push({ path: file.path, kind: 'plugin', op: 'leave-absent' }); continue }
      units.push({ path: file.path, kind: 'plugin', op: current === null ? 'create' : current === file.digest ? 'keep' : 'replace', baseDigest: current, candidateDigest: file.digest, bytes: file.bytes, mode: file.mode })
      continue
    }
    const base = trusted.get(file.path)
    const op = base === undefined ? 'create' : base === file.digest ? 'keep' : 'replace'
    units.push({ path: file.path, kind: file.kind, op, baseDigest: base ?? null, candidateDigest: file.digest, bytes: file.bytes })
  }
  for (const [notePath, digest] of [...trusted].sort(([left], [right]) => (left < right ? -1 : 1))) {
    if (!present.has(notePath)) units.push({ path: notePath, kind: priorAttachments.has(notePath) || (underAttachments && notePath.startsWith('attachments/')) ? 'attachment' : 'note', op: 'remove', baseDigest: digest, candidateDigest: null })
  }
  units.forEach((unit, index) => { unit.unit = index })
  return units
}

// The rules the oracle tests are sensitive to. Production always uses these; the tests substitute a deliberately
// broken one through publishViewForOracleTests to prove the oracle can fail.
export const PUBLICATION_PRIMITIVES = Object.freeze({
  // The one operation the `direct-unheld` path writes into the vault: a file created where nothing is.
  unheldWrites: (op) => op === 'create',
  // Whether an error that stopped staging was the caller's stop (its settings check, or a cancellation), handed on
  // under its own code once the candidates are cleaned up, rather than reported as a staging failure.
  callerStoppedStaging: (error) => isSchedulingStop(error),
})

// Whether the `direct-unheld` path applies, after the adapter found an app it cannot coordinate with (see the head of
// this file). Every condition must hold; an evidence reader that is absent, throws or answers anything but
// `unlisted: true` gives none.
async function unheldPathApplies({ probe, pointer, store, unheldEvidence, platform }) {
  if (probe.code !== undefined || pointer !== null) return false
  if (platform !== 'darwin' && platform !== 'linux') return false
  const { allocation } = store
  if (store.vaultOrigin !== 'allocated' || store.managedVaultRoot !== true || !allocation || store.vaultRoot !== allocation.path || allocatedFolderState(allocation) !== 'same') return false
  return readsUnlisted(unheldEvidence, store)
}

async function readsUnlisted(unheldEvidence, store) {
  if (typeof unheldEvidence !== 'function') return false
  try { return (await unheldEvidence({ vaultRoot: store.vaultRoot }))?.unlisted === true } catch { return false }
}

export function publishView(options = {}) {
  return publishViewForOracleTests(options, PUBLICATION_PRIMITIVES)
}

export async function publishViewForOracleTests(options = {}, primitives = PUBLICATION_PRIMITIVES) {
  const { preparedView, protocolId, expectedGeneration, recoveryStore: store, adapter, clock = () => new Date(), quietPeriodMs = 1500, exchangeOptions = {} } = options
  // `unheldEvidence({ vaultRoot })` answers whether the app's own list names this vault (see the head of this file).
  const { unheldEvidence = null, platform = process.platform } = options
  const rules = { ...PUBLICATION_PRIMITIVES, ...primitives }
  const seam = options[CRASH_INJECTION_TEST_SEAM] ?? null
  const crash = (point) => { if (seam && seam.at === point) seam.halt(point) }
  if (!store || typeof store.commitManifest !== 'function') throw new TypeError('publishView needs a recoveryStore')
  if (!adapter || typeof adapter.probe !== 'function') throw new TypeError('publishView needs an editor coordination adapter')
  if (expectedGeneration !== null && typeof expectedGeneration !== 'string') throw new TypeError('expectedGeneration must be a generation identity or null')

  const budget = createCooperativeBudget(options.scheduling)
  budget.check()
  const releases = []
  let journal = null
  try {
    if (protocolId !== PROTOCOL_ID) refuse('unknown-protocol', 'the publisher implements exactly one publication protocol')
    const { manifest, manifestBytes } = validatePreparedView(preparedView, store)
    // A release that could not be written (a full disk) is finished first.
    for (const lockPath of [store.vaultLockPath, store.lockPath]) {
      if (!unreleased.has(lockPath)) continue
      try { unreleased.get(lockPath)() } catch (error) { if (!lockFolderGone(error)) refuse('state-unwritable', 'private publication state cannot be written; nothing in the vault was touched', { cause: error.code ?? String(error.message) }) }
      unreleased.delete(lockPath)
    }
    // Two locks, the view's and then the vault's: a second view or a second
    // workspace state pointed at the same vault refuses instead of racing.
    const acquire = (lockPath, take, held) => {
      try { releases.push([lockPath, take()]) } catch (error) {
        if (error instanceof PublicationRefusal) throw error
        if (error.code === 'EEXIST') refuse('publication-in-progress', `another publication ${held} holds the lock`)
        refuse('state-unwritable', 'private publication state cannot be written; nothing in the vault was touched', { cause: error.code ?? String(error.message) })
      }
    }
    acquire(store.lockPath, () => acquirePrivateLock(store.lockPath), 'of this view')
    // A vault allocated for the view is still the folder it made, before anything is written in it (the vault lock
    // included) and again once the lock is held: a store kept by a long-running service may outlive its folder. It is
    // checked again after every wait on the app, before each unit and before the commit, so a folder replaced during a
    // publication refuses it and is never reported current. (Only this account can replace it; the check and the
    // write that follows it are still two steps.)
    store.checkAllocatedVault?.()
    acquire(store.vaultLockPath, () => acquireVaultLock(store), 'into this vault')
    store.checkAllocatedVault?.()
    await budget.checkpoint('recover', true)
    store.checkAllocatedVault?.()
    const recovered = recoverPublicationsLocked({ store, clock })
    await budget.checkpoint('recovery-complete', true)
    store.checkAllocatedVault?.()
    const pointer = store.readCurrent()
    if (pointer?.generationId === manifest.generationId && !pluginFilesDrifted(preparedView, store)) {
      await options.beforeCommit?.()
      budget.check()
      store.checkAllocatedVault?.()
      return { state: 'committed', alreadyCommitted: true, generationId: manifest.generationId, journalId: pointer.journalId, notes: [], retainedEdits: pointer.retained ?? [], lateWriters: [], recovered }
    }
    if ((pointer?.generationId ?? null) !== expectedGeneration) refuse('generation-mismatch', 'the committed generation is not the one this publication expects', { committed: pointer?.generationId ?? null })

    // Path selection. An app with this vault open in several windows is refused as such: publishing through one of
    // them would leave the others uncoordinated.
    const probe = await adapter.probe({ vaultRoot: store.vaultRoot })
    store.checkAllocatedVault?.()
    const unheld = probe.state !== 'coordinated' && probe.state !== 'absent' && await unheldPathApplies({ probe, pointer, store, unheldEvidence, platform })
    // The evidence took time to read: the folder is checked again.
    if (unheld) store.checkAllocatedVault?.()
    if (probe.state !== 'coordinated' && probe.state !== 'absent' && !unheld) refuse(probe.code === 'vault-open-in-several-windows' ? probe.code : 'editor-uncoordinated', `an Obsidian process may have this vault open and cannot be coordinated with: ${probe.reason}`)
    const mode = probe.state === 'coordinated' ? 'in-app' : unheld ? 'direct-unheld' : 'direct'
    const channel = mode === 'in-app' ? adapter : createDirectAdapter({ crashSeam: seam })

    // Same volume, and an exchange that works on it.
    const vaultDevice = fs.statSync(store.vaultRoot).dev
    // Candidates are exchanged from the recovery area, so that is where the
    // exchange is proven; staging must share the volume because candidates are moved from it.
    let probeDir
    try { probeDir = store.exchangeProbeDir() } catch (error) { refuse('state-unwritable', 'private publication state cannot be written; nothing in the vault was touched', { cause: error.code ?? String(error.message) }) }
    if ([store.stagingRoot, store.resolve('recovery'), probeDir].some((directory) => fs.statSync(directory).dev !== vaultDevice)) {
      refuse('staging-volume-mismatch', 'staging and recovery must be on the volume that holds the vault')
    }
    const exchange = probeExchange({ directory: probeDir, ...exchangeOptions })
    if (!exchange.supported) refuse(exchange.code, exchange.message)

    const pluginDisk = new Map(preparedView.files.filter((file) => file.kind === 'plugin').map((file) => [file.path, currentDigestOf(store.vaultRoot, file.path)]))
    const units = planUnits({ files: preparedView.files, priorManifest: store.readCurrentManifest(), pointer, ledger: publishedSinceCommit({ store }), pluginDisk })

    // Stage every known candidate before anything is touched.
    const journalId = newJournalId(clock)
    const created = []
    const moved = []
    let stagingDir = null
    try {
      stagingDir = store.stagingDir(journalId)
      // On the `direct-unheld` path a replacement is never written, so no candidate is staged for one.
      for (const unit of units.filter((item) => item.op === 'create' || (item.op === 'replace' && (mode !== 'direct-unheld' || rules.unheldWrites(item.op))))) {
        await budget.checkpoint('stage-candidate')
        store.checkAllocatedVault?.()
        const existing = fs.lstatSync(path.join(store.vaultRoot, unit.path), { throwIfNoEntry: false })
        unit.preparedPath = store.preparedPath(journalId, unit.unit)
        stageCandidate(unit.preparedPath, unit.bytes, unit.mode ?? (existing?.isFile() ? existing.mode & 0o777 : 0o644), created)
        // A replacement is exchanged, and the exchange leaves the displaced bytes at this path: it is in recovery.
        unit.stagedPath = unit.op === 'replace' ? store.exchangeCandidatePath(journalId, unit.unit) : unit.preparedPath
      }
      await budget.checkpoint('staging-complete', true)
      store.checkAllocatedVault?.()
      syncPrivateDirectory(stagingDir)
      const manifestFile = path.join(store.journalDir(journalId), 'manifest.json')
      publishPrivateFile(manifestFile, manifestBytes)
      journal = createJournal(store, { journalId, protocolId, expectedGeneration, targetGeneration: manifest.generationId, clock,
        detail: { mode, manifestRef: store.ref(manifestFile), manifestDigest: sha256Digest(manifestBytes),
          // The units this run may write. A kept note is compared and never written; the one case that writes
          // it after all (a kept note gone missing) is a late candidate with its own write-ahead entry.
          units: units.filter((item) => item.op !== 'keep' && item.op !== 'leave-absent').map(({ unit, path: unitPath, kind, op }) => ({ unit, path: unitPath, kind, op })),
          staged: units.filter((item) => item.stagedPath).map((item) => ({ unit: item.unit, path: item.path, candidateDigest: item.candidateDigest, stagedRef: store.ref(item.stagedPath),
            ...(item.stagedPath === item.preparedPath ? {} : { preparedRef: store.ref(item.preparedPath) }) })) } })
      crash('before-candidate-move')
      // The journal now names every exchange candidate by path and digest. Only complete, fsynced files are moved
      // in, so a file at an exchange path is never a partial candidate.
      for (const unit of units.filter((item) => item.stagedPath && item.stagedPath !== item.preparedPath)) {
        await budget.checkpoint('move-candidate')
        store.checkAllocatedVault?.()
        moveToExchangePath(store, journalId, unit, moved)
      }
    } catch (error) {
      const stopped = rules.callerStoppedStaging(error)
      if (error instanceof PublicationRefusal && !stopped) throw error
      // No payload has named any of these paths, so nothing was exchanged and they can only hold our own
      // candidates. In staging they are removed by name. In recovery a file is removed only when its bytes are
      // the candidate's; anything else stays for restart recovery, which the journal header points at it. Only
      // empty directories are removed, so a failed staging leaves nothing that looks like an unfinished unit.
      for (const unit of moved) {
        if (readFileDigest(unit.stagedPath) === unit.candidateDigest) fs.rmSync(unit.stagedPath, { force: true })
        try { fs.rmdirSync(path.dirname(unit.stagedPath)) } catch { /* not empty: left for restart recovery */ }
      }
      for (const file of created) fs.rmSync(file, { force: true })
      for (const directory of [stagingDir, store.unitsRoot(journalId)]) if (directory) try { fs.rmdirSync(directory) } catch { /* absent, or not empty */ }
      // The caller stopped the publication between two candidates: nothing failed to stage, and its reason (a
      // setting that changed during the tick, `mixed-read`, or a cancellation) is the one reported.
      if (stopped) throw error
      refuse('staging-failed', 'the candidates could not be staged; nothing in the vault was touched', { cause: error.code ?? String(error.message) })
    }
    await budget.checkpoint('journal-and-moves-complete', true)
    store.checkAllocatedVault?.()
    crash('after-staging')

    const context = { store, journal, journalId, channel, clock, crash, mode, rules }
    const results = []
    // Kept notes are compared first, several at a time; one that holds exactly its candidate bytes is unchanged.
    const unchanged = await unchangedKeepUnits(units, store)
    // The direct path has no editor coordination, so it is only right while no
    // Obsidian runs. Staging takes time and an app may have started since path
    // selection: the process table is read again immediately before the first
    // note, whatever time has passed, and again whenever two seconds have
    // passed since the last reading. An app that starts after a reading and
    // before the next is not seen; that window is at most two seconds plus
    // one note's publication.
    // The `direct-unheld` path reads its evidence on the same schedule, and once a reading gives none, every remaining
    // unit refuses, a kept one included, so nothing is committed.
    let lastProbe = null
    for (const unit of units) {
      await budget.checkpoint('publish-unit')
      store.checkAllocatedVault?.()
      if (mode === 'direct' && (lastProbe === null || Date.now() - lastProbe > 2000)) {
        lastProbe = Date.now()
        const again = await adapter.probe({ vaultRoot: store.vaultRoot })
        if (again.state !== 'absent') context.uncoordinated = again.reason
      }
      if (mode === 'direct-unheld' && !context.uncoordinated && (lastProbe === null || Date.now() - lastProbe > 2000)) {
        lastProbe = Date.now()
        if (!(await readsUnlisted(unheldEvidence, store))) context.uncoordinated = 'the vault list of the app no longer shows, positively, that no Obsidian lists this vault'
      }
      store.checkAllocatedVault?.()
      if (unit.op === 'keep' && unchanged.has(unit.path)) {
        results.push({ path: unit.path, kind: unit.kind, op: unit.op, outcome: context.uncoordinated ? 'editor-uncoordinated' : 'unchanged', blocking: mode === 'direct-unheld' && Boolean(context.uncoordinated) })
        continue
      }
      try { results.push(await publishUnit(unit, context)) } catch (error) {
        if (error.code !== 'ELEAFCHANGED') throw error
        // Another program kept replacing this file while it was read: its bytes are left as they are, the unit's
        // journal stays open for recovery like an interrupted one, and the other units go on.
        results.push({ path: unit.path, kind: unit.kind, op: unit.op, outcome: 'disk-changed', blocking: true })
      }
    }

    await budget.checkpoint('publication-complete', true)
    store.checkAllocatedVault?.()
    const blocking = results.filter((result) => result.blocking)
    const retainedEdits = results.filter((result) => result.retained).map((result) => result.retained)
    // Notes kept earlier stay surfaced until they leave the vault or come back into a view.
    const base = { journalId, generationId: manifest.generationId, mode, notes: results.map(({ retained, ...rest }) => rest), retainedEdits, recovered }
    if (blocking.length > 0 || (mode === 'direct-unheld' && context.uncoordinated)) {
      const lateWriters = recheckDisplacedFiles({ store, journalIds: [journalId], clock })
      return { ...base, state: 'updating', lateWriters }
    }

    // Quiet period, then look at the displaced files again.
    if (quietPeriodMs > 0 && results.some((result) => result.recoveryRef)) await sleep(quietPeriodMs)
    const lateWriters = recheckDisplacedFiles({ store, journalIds: [journalId], clock })
    for (const finding of lateWriters.filter((item) => item.code === 'late-writer-captured')) {
      journal.append({ step: 'verify', outcome: 'conflict', state: 'verifying', notePath: finding.notePath, beforeDigest: finding.digestAtMove, afterDigest: finding.observedDigest, recoveryRef: finding.displacedRef,
        detail: { unit: finding.unit, code: 'late-writer-captured', objectRef: finding.objectRef } })
    }
    await budget.checkpoint('verify-before-commit', true)
    // The resident engine revalidates the selected source pins here, while
    // publication still owns its locks. Its check may yield; no durability
    // unit or committed pointer is half-written across that wait. It comes
    // before the entry that says the publication settled: restart recovery
    // commits a journal that holds that entry, so a refusal after it would be
    // committed by the next publication of this view.
    await options.beforeCommit?.()
    budget.check()
    store.checkAllocatedVault?.()
    journal.append({ step: 'verify', outcome: 'ok', state: 'verifying', detail: { settled: true, retained: retainedEdits } })
    crash('before-manifest-commit')
    store.checkAllocatedVault?.()
    store.commitManifest({ manifestBytes, generationId: manifest.generationId, journalId, retained: retainedEdits, committedAt: iso(clock) })
    crash('after-manifest-pointer')
    journal.append({ step: 'manifest-commit', outcome: 'ok', state: 'committed', detail: { manifestDigest: sha256Digest(manifestBytes) } })
    journal.close()
    try { fs.rmdirSync(store.stagingDir(journalId)) } catch { /* something is still staged; restart recovery looks at it */ }
    return { ...base, state: 'committed', lateWriters }
  } catch (error) {
    if (!(error instanceof PublicationRefusal)) {
      if (journal) try { journal.append({ step: 'verify', outcome: 'failed', state: 'failed', detail: { code: 'publisher-error', message: String(error.code ?? error.message).slice(0, 200) } }) } catch { /* the journal itself cannot be written */ }
      throw error
    }
    return { state: 'refused', refusal: { code: error.code, message: error.message, detail: error.detail }, notes: [], retainedEdits: [], lateWriters: [] }
  } finally {
    // A release that fails is kept and tried again before the next publication of that lock, even when the lock's folder
    // is not there now: a vault moved away keeps its ticket and may be put back.
    for (const [lockPath, release] of releases.reverse()) try { release() } catch { unreleased.set(lockPath, release) }
  }
}

// ---------------------------------------------------------------------------
// One note, attachment, settings file or plugin file
// ---------------------------------------------------------------------------

// Atelier's own plugin never waits on a person: a plugin path that cannot be
// written safely, a vault root not private enough for the bearer, or a file
// that could not be made or replaced there (a plugin folder the person can read
// but not write, say) is reported and left for the person while every note
// converges, and its candidate is retired at once. A plugin file that another
// writer changed under this run is a race: it blocks like a note, so the view
// is tried again and the file is planned from the disk anew. Nothing reads a
// plugin file as a person's edit of a note: its outcomes carry their own names.
const PLUGIN_LEFT_FOR_A_PERSON = new Set(['path-unsafe', 'vault-not-private', 'create-failed', 'exchange-failed'])
// A leaf or a parent nobody may look into or read (another owner, mode 000) or a link loop: the person's to repair,
// like a leaf that is not a file. It is reported, never thrown, so the rest of the view and every later view go on.
const UNREADABLE_PATH = new Set(['EACCES', 'EPERM', 'ELOOP'])
const PLUGIN_FILE_CHANGED = new Set(['edit-kept', 'disk-changed', 'editor-edit'])

async function publishUnit(unit, context) {
  let result
  try { result = await publishOneUnit(unit, context) } catch (error) {
    // A plugin or settings file another program kept replacing while it was opened (see readNote) is a race of that
    // file, like one that changed under the run: blocking, tried again, and never taken for a person's edit of a note.
    if (error?.code !== 'ELEAFCHANGED' || (unit.kind !== 'plugin' && unit.kind !== 'settings')) throw error
    // Its candidate is left as #83 leaves a note's: the unit's journal stays open for recovery like an interrupted one.
    result = { path: unit.path, kind: unit.kind, op: unit.op, outcome: unit.kind === 'settings' ? 'settings-changed' : 'disk-changed', blocking: true }
  }
  if (unit.kind !== 'plugin') return result
  const { changedAfterPublication, retained: _retained, ...rest } = result
  if (rest.outcome === 'path-unsafe' && unit.stagedPath) retire(unit, context)
  const changed = PLUGIN_FILE_CHANGED.has(rest.outcome)
  return { ...rest, outcome: changed ? 'plugin-file-changed' : rest.outcome, blocking: changed || (rest.blocking && !PLUGIN_LEFT_FOR_A_PERSON.has(rest.outcome)), ...(changedAfterPublication ? { pluginFileChanged: true } : {}) }
}

// The vault root holds the plugin's bearer once its data file is there, so it
// must be private to this user. A vault root Atelier placed under its own data
// root is made private here; any other one is only looked at, and a vault path
// under the data root that is a link to somewhere else never receives it.
function ensurePrivateVaultRoot(store) {
  if (store.linkedVaultRoot === true) return { private: false, reason: 'vault-root-is-a-link' }
  const uid = typeof process.getuid === 'function' ? process.getuid() : null
  let stat = fs.lstatSync(store.vaultRoot, { throwIfNoEntry: false })
  if (!stat?.isDirectory() || uid === null || stat.uid !== uid) return { private: false, reason: 'vault-root-not-owned' }
  if ((stat.mode & 0o077) !== 0 && store.managedVaultRoot === true) {
    try { fs.chmodSync(store.vaultRoot, stat.mode & 0o700) } catch { /* looked at again below */ }
    stat = fs.lstatSync(store.vaultRoot, { throwIfNoEntry: false })
  }
  return stat?.isDirectory() && (stat.mode & 0o077) === 0 ? { private: true } : { private: false, reason: 'vault-root-not-private' }
}

async function publishOneUnit(unit, context) {
  const { store, journal, journalId, clock } = context
  const note = path.join(store.vaultRoot, unit.path)
  const outcome = (code, extra = {}) => ({ path: unit.path, kind: unit.kind, op: unit.op, outcome: code, blocking: false, ...extra })
  // On the `direct-unheld` path a unit after a failed reading refuses, whatever it would have done, so the run says why
  // it stopped.
  if (unit.op === 'leave-absent') return context.mode === 'direct-unheld' && context.uncoordinated ? outcome('editor-uncoordinated', { blocking: true }) : outcome('left-absent')
  const observe = (bytes) => store.retainObject(bytes)
  if (context.uncoordinated) return outcome('editor-uncoordinated', { blocking: unit.op !== 'keep' || context.mode === 'direct-unheld' })
  // The `direct-unheld` path creates files and nothing else. A unit planned as a replacement or a removal has no
  // candidate staged, and is refused before its file is even read. (A kept unit may still become a create; a settings
  // unit is decided in planSettings.)
  if (context.mode === 'direct-unheld' && unit.op !== 'keep' && unit.op !== 'settings' && !context.rules.unheldWrites(unit.op)) return outcome('editor-uncoordinated', { blocking: true })
  // A settings path that cannot be written safely (a symlinked `.obsidian`,
  // say) is reported and left alone; it must not keep every note from
  // converging while the person repairs it. Notes and attachments block.
  const unsafeBlocks = unit.op !== 'settings'
  const unreadable = (error) => { if (!UNREADABLE_PATH.has(error?.code)) throw error; return outcome('path-unsafe', { blocking: unsafeBlocks, errorCode: error.code }) }
  let leaf
  try {
    if (!ensureParents(store.vaultRoot, unit.path)) return outcome('path-unsafe', { blocking: unsafeBlocks })
    leaf = fs.lstatSync(note, { throwIfNoEntry: false })
  } catch (error) { return unreadable(error) }
  if (leaf && !leaf.isFile()) return outcome('path-unsafe', { blocking: unsafeBlocks })

  let plan = unit
  if (unit.op === 'settings') {
    plan = planSettings(unit, context)
    if (plan.outcome) return plan
  }
  let current
  try { current = readNote(note) } catch (error) { return unreadable(error) }
  const currentDigest = current === null ? null : sha256Digest(current)

  if (plan.op === 'keep') {
    if (currentDigest === plan.candidateDigest) return outcome('unchanged')
    if (current === null) {
      let stagedPath
      try { stagedPath = stageLate(plan, context) } catch (error) {
        return outcome('staging-failed', { blocking: true, errorCode: error.code ?? null })
      }
      plan = { ...plan, op: 'create', stagedPath }
    }
    else {
      // Generated bytes did not change and the person's did: nothing to write, nothing to lose.
      const object = observe(current)
      return outcome('edit-kept', { observedDigest: currentDigest, objectRef: object.ref })
    }
  }
  if (plan.op === 'replace' && current === null) plan = { ...plan, op: 'create' }
  if (plan.op === 'remove' && current === null) return outcome('already-absent')
  if (plan.op !== 'remove' && currentDigest !== null && currentDigest === plan.candidateDigest) {
    if (plan.stagedPath) retire(plan, context)
    return outcome('already-current')
  }
  // Whatever a unit became on the way here, the `direct-unheld` path writes nothing below this point but a create.
  if (context.mode === 'direct-unheld' && !context.rules.unheldWrites(plan.op)) {
    if (plan.stagedPath) retire(plan, context)
    return outcome('editor-uncoordinated', { blocking: true })
  }

  if (unit.path === PLUGIN_DATA_PATH && plan.op !== 'remove') {
    const privacy = ensurePrivateVaultRoot(store)
    if (!privacy.private) {
      if (plan.stagedPath) retire(plan, context)
      return outcome('vault-not-private', { reason: privacy.reason })
    }
  }

  const operationId = `${journalId}:${unit.unit}`
  const displaced = plan.op === 'create' ? null : store.displacedPath(journalId, unit.unit)
  // The journal state never goes backwards: once a note has been published the transition is `updating`.
  const capture = (result, code, extra = {}) => journal.append({ step: 'capture', outcome: result, state: context.updating ? 'updating' : 'captured', notePath: unit.path,
    ...(extra.beforeDigest ? { beforeDigest: extra.beforeDigest } : {}), ...(result === 'ok' && plan.candidateDigest ? { afterDigest: plan.candidateDigest } : {}),
    ...(extra.recoveryRef ? { recoveryRef: extra.recoveryRef } : {}), detail: { unit: unit.unit, op: plan.op, kind: unit.kind, code, ...(extra.detail ?? {}) } })
  const settle = (result, code, extra = {}) => journal.append({ step: 'conditional-update', outcome: result, state: (context.updating ||= result === 'ok') ? 'updating' : 'captured', notePath: unit.path,
    ...(plan.baseDigest ? { beforeDigest: plan.baseDigest } : {}), ...(result === 'ok' && plan.candidateDigest ? { afterDigest: plan.candidateDigest } : {}),
    ...(extra.recoveryRef ? { recoveryRef: extra.recoveryRef } : {}), detail: { unit: unit.unit, op: plan.op, kind: unit.kind, code, ...(extra.externalCaptured ? { externalCaptured: true } : {}) } })

  if (plan.op === 'create') {
    if (current !== null) {
      // A file appeared where a new note would go. It is not ours: keep it.
      const object = observe(current)
      capture('conflict', 'create-conflict', { beforeDigest: currentDigest, recoveryRef: object.ref })
      retire(plan, context)
      return outcome('create-conflict', { blocking: true, observedDigest: currentDigest, objectRef: object.ref })
    }
    capture('ok', 'intent', { detail: { intent: true, operationId, stagedRef: store.ref(plan.stagedPath) } })
    context.crash('after-capture')
    try {
      // Exclusive create: a hard link either makes the complete file appear or fails because something is there.
      fs.linkSync(plan.stagedPath, note)
    } catch (error) {
      retire(plan, context)
      settle(error.code === 'EEXIST' ? 'conflict' : 'failed', error.code === 'EEXIST' ? 'create-conflict' : 'create-failed')
      return outcome(error.code === 'EEXIST' ? 'create-conflict' : 'create-failed', { blocking: true, errorCode: error.code })
    }
    context.crash('after-publish')
    fs.unlinkSync(plan.stagedPath)
    syncPrivateDirectory(path.dirname(note))
    settle('ok', 'created')
    return verify(unit, plan, context, outcome('created'))
  }

  // replace and remove: the comparison baseline is retained before anything moves.
  if (currentDigest !== plan.baseDigest) {
    const object = observe(current)
    capture('conflict', 'disk-changed', { beforeDigest: currentDigest, recoveryRef: object.ref })
    if (plan.stagedPath) retire(plan, context)
    const retained = { path: unit.path, priorDigest: plan.baseDigest, observedDigest: currentDigest, objectRef: object.ref }
    // An edited note that left the scope is never deleted. It stays in the vault and stays surfaced.
    if (plan.op === 'remove') return outcome('retained-edit', { retained, observedDigest: currentDigest, objectRef: object.ref })
    return outcome('disk-changed', { blocking: true, observedDigest: currentDigest, objectRef: object.ref })
  }
  const baseObject = observe(current)
  const inspected = await context.channel.inspect({ vaultRoot: store.vaultRoot, path: unit.path })
  if (inspected.status !== 'inspected') {
    capture('failed', inspected.status, { beforeDigest: currentDigest })
    if (plan.stagedPath) retire(plan, context)
    return outcome(inspected.status, { blocking: true })
  }
  if (inspected.views.some((view) => view.dirty || view.bufferSha256 !== hex(plan.baseDigest))) {
    capture('conflict', 'editor-edit', { beforeDigest: currentDigest, recoveryRef: baseObject.ref })
    if (plan.stagedPath) retire(plan, context)
    return outcome('editor-edit', { blocking: true, openViews: inspected.views.length })
  }
  capture('ok', 'intent', { beforeDigest: plan.baseDigest, recoveryRef: store.ref(displaced),
    detail: { intent: true, operationId, baseObjectRef: baseObject.ref, openViews: inspected.views.length, ...(plan.stagedPath ? { stagedRef: store.ref(plan.stagedPath) } : {}) } })
  context.crash('after-capture')

  const reply = await context.channel.publish(plan.op === 'remove'
    ? { op: 'publish', mode: 'remove', vaultRoot: store.vaultRoot, path: unit.path, operationId, baseSha256: hex(plan.baseDigest), recoveryPath: displaced }
    : { op: 'publish', mode: 'replace', vaultRoot: store.vaultRoot, path: unit.path, operationId, baseSha256: hex(plan.baseDigest), candidateSha256: hex(plan.candidateDigest), stagedPath: plan.stagedPath, recoveryPath: displaced })
  context.crash('after-publish')

  if (reply.status === 'published' || reply.status === 'published-external-captured' || reply.status === 'removed' || reply.status === 'removed-external-captured') {
    syncPrivateDirectory(path.dirname(displaced))
    const recorded = recordDisplaced({ store, journalId, unit: unit.unit, notePath: unit.path, displacedPath: displaced, baseDigest: plan.baseDigest, at: iso(clock),
      digestAtMove: /^[0-9a-f]{64}$/.test(reply.recoveredSha256 ?? '') ? `sha256:${reply.recoveredSha256}` : null })
    const code = plan.op === 'remove' ? (recorded.externalCaptured ? 'removed-external-captured' : 'removed') : (recorded.externalCaptured ? 'published-external-captured' : 'published')
    settle('ok', code, { recoveryRef: recorded.displacedRef, externalCaptured: recorded.externalCaptured })
    const result = outcome(code, { recoveryRef: recorded.displacedRef, externalCaptured: recorded.externalCaptured, openViews: reply.openViews ?? 0, replyLost: reply.replyLost === true,
      ...(plan.op === 'remove' && recorded.externalCaptured ? { retained: { path: unit.path, priorDigest: plan.baseDigest, observedDigest: recorded.digestAtMove, recoveryRef: recorded.displacedRef, movedToRecovery: true } } : {}) })
    return plan.op === 'remove' ? result : verify(unit, plan, context, result)
  }

  if (reply.status === 'outcome-unknown') {
    // No reply and no recorded outcome. The files say what happened; the publish is not sent again.
    const captureEntry = journal.document().entries.findLast((entry) => entry.step === 'capture' && entry.notePath === unit.path)
    const entry = reconcileUnit({ store, journalId, capture: captureEntry, at: iso(clock) })
    journal.append({ ...entry, state: (context.updating ||= entry.outcome === 'ok') ? 'updating' : 'captured' })
    if (entry.outcome === 'ok') {
      const result = outcome(entry.detail.code, { recoveryRef: entry.recoveryRef, externalCaptured: entry.detail.externalCaptured === true, replyLost: true })
      return plan.op === 'remove' ? result : verify(unit, plan, context, result)
    }
    return outcome('outcome-unknown-nothing-published', { blocking: true, replyLost: true })
  }

  if (plan.stagedPath) retire(plan, context)
  if (reply.status === 'remove-reverted') {
    // The put-back may have left its second name behind. It names the live note, not displaced bytes: it gets no
    // receipt, and it is removed here when it still is that very file.
    const [live, left] = [fs.lstatSync(note, { throwIfNoEntry: false }), fs.lstatSync(displaced, { throwIfNoEntry: false })]
    if (live && left && live.ino === left.ino && live.dev === left.dev) try { fs.unlinkSync(displaced) } catch { /* the late-writer check skips a name that is the live note */ }
    settle('conflict', 'remove-reverted')
    const bytes = readNote(note)
    const object = bytes === null ? null : observe(bytes)
    return outcome('retained-edit', { retained: { path: unit.path, priorDigest: plan.baseDigest, observedDigest: bytes === null ? null : sha256Digest(bytes), ...(object ? { objectRef: object.ref } : {}) } })
  }
  if (reply.status === 'note-missing' && plan.op === 'remove') {
    settle('ok', 'already-absent')
    return outcome('already-absent')
  }
  const conflict = REFUSED_BY_EDIT.has(reply.status) || reply.status === 'note-missing'
  // Whatever is at the path now is somebody's edit: keep a copy before reporting the refusal.
  const seen = REFUSED_BY_EDIT.has(reply.status) ? readNote(note) : null
  const seenObject = seen === null || sha256Digest(seen) === plan.baseDigest ? null : observe(seen)
  settle(conflict ? 'conflict' : 'failed', reply.status, seenObject ? { recoveryRef: seenObject.ref } : {})
  return outcome(reply.status, { blocking: true, ...(seenObject ? { observedDigest: seenObject.digest, objectRef: seenObject.ref } : {}), ...(reply.exitStatus === undefined ? {} : { exitStatus: reply.exitStatus }) })
}

// Moves a complete candidate from staging to the path it will be exchanged from.
function moveToExchangePath(store, journalId, unit, moved = []) {
  store.unitDir(journalId, unit.unit)
  moved.push(unit)
  fs.renameSync(unit.preparedPath, unit.stagedPath)
  syncPrivateDirectory(path.dirname(unit.stagedPath))
}

function retire(plan, { store, journalId, crash }) {
  const result = retireStagedFile({ store, journalId, unit: plan.unit, stagedPath: plan.stagedPath, candidateDigest: plan.candidateDigest, crash })
  for (const capturedPath of result.capturedPaths) recordDisplaced({ store, journalId, unit: plan.unit, notePath: plan.path, displacedPath: capturedPath, baseDigest: plan.baseDigest ?? null, at: new Date().toISOString() })
}

// A candidate that could not be known when the run began (settings merged from
// the bytes on disk now; a kept note that has gone missing). One that will be
// created stays in staging. One that will be exchanged goes to the unit's
// recovery directory like any other, and because the header could not name
// it, a write-ahead entry names its path and digest before it is moved there:
// restart recovery can then tell this generated file from displaced bytes.
// A late candidate that fails part-way is removed before the failure is
// reported: nothing names it, so nothing would ever clean it up.
function stageLate(plan, { store, journal, journalId, crash, updating }) {
  const preparedPath = store.preparedPath(journalId, plan.unit, { late: true })
  const created = []
  try { stageCandidate(preparedPath, plan.bytes, plan.mode ?? 0o644, created, crash) } catch (error) {
    for (const file of created) fs.rmSync(file, { force: true })
    throw error
  }
  if (plan.op !== 'replace') return preparedPath
  const unit = { unit: plan.unit, preparedPath, stagedPath: store.exchangeCandidatePath(journalId, plan.unit, { late: true }) }
  journal.append({ step: 'capture', outcome: 'ok', state: updating ? 'updating' : 'captured', notePath: plan.path, afterDigest: plan.candidateDigest,
    detail: { unit: plan.unit, op: plan.op, kind: plan.kind, code: 'late-candidate', intent: false, stagedRef: store.ref(unit.stagedPath), preparedRef: store.ref(preparedPath) } })
  crash('after-late-write-ahead')
  moveToExchangePath(store, journalId, unit)
  return unit.stagedPath
}

// Policy settings are owned per key or entry. The candidate is the file on
// disk now with only what Atelier owns set; the base is that same file. A file
// whose shape the policy does not know is the person's to repair and is left
// alone.
function planSettings(unit, context) {
  const note = path.join(context.store.vaultRoot, unit.path)
  let existing
  try { existing = readNote(note) } catch (error) {
    if (!UNREADABLE_PATH.has(error?.code)) throw error
    return { path: unit.path, kind: 'settings', op: 'settings', outcome: 'path-unsafe', blocking: false, errorCode: error.code }
  }
  // Prepared from other bytes than these: the person changed the file since, and whatever Atelier decided from the old
  // bytes is not written over the change. The view is tried again, and the next preparation reads the file as it is.
  if (Object.hasOwn(unit, 'expectedDigest') && (existing === null ? null : sha256Digest(existing)) !== unit.expectedDigest) {
    return { path: unit.path, kind: 'settings', op: 'settings', outcome: 'settings-changed', blocking: true }
  }
  // On the `direct-unheld` path a settings file that is there is never written over, and no candidate is staged for it.
  // Only one that already holds exactly what the policy asks (Atelier's own, from an interrupted run) is left as it is.
  if (context.mode === 'direct-unheld' && existing !== null && !context.rules.unheldWrites('replace') && !holdsPolicy(unit.path, existing)) {
    return { path: unit.path, kind: 'settings', op: 'settings', outcome: 'editor-uncoordinated', blocking: true }
  }
  let file
  try { file = preparePolicySettingsFile(unit.path, existing) } catch (error) {
    if (error instanceof ObsidianContractRefusal) return { path: unit.path, kind: 'settings', op: 'settings', outcome: 'settings-invalid', blocking: false }
    throw error
  }
  if (existing !== null && file.bytes.equals(existing)) return { path: unit.path, kind: 'settings', op: 'settings', outcome: 'policy-satisfied', blocking: false }
  const plan = { ...unit, op: existing === null ? 'create' : 'replace', baseDigest: existing === null ? null : sha256Digest(existing), candidateDigest: file.digest, bytes: file.bytes,
    mode: existing === null ? 0o644 : fs.lstatSync(note).mode & 0o777 }
  try { plan.stagedPath = stageLate(plan, context) } catch (error) {
    return { path: unit.path, kind: 'settings', op: 'settings', outcome: 'staging-failed', blocking: true, errorCode: error.code }
  }
  return plan
}

function holdsPolicy(settingsPath, bytes) {
  try { return preparePolicySettingsFile(settingsPath, bytes).bytes.equals(bytes) } catch (error) {
    if (error instanceof ObsidianContractRefusal) return false
    throw error
  }
}

function verify(unit, plan, { store, journal }, result) {
  const bytes = readNote(path.join(store.vaultRoot, unit.path))
  const digest = bytes === null ? null : sha256Digest(bytes)
  if (digest === plan.candidateDigest) {
    journal.append({ step: 'verify', outcome: 'ok', state: 'updating', notePath: unit.path, afterDigest: digest, detail: { unit: unit.unit, code: 'verified' } })
    return result
  }
  // Published, then changed by someone else. That is an edit on top of this generation, kept where it is.
  const object = bytes === null ? null : store.retainObject(bytes)
  journal.append({ step: 'verify', outcome: 'conflict', state: 'updating', notePath: unit.path, ...(digest ? { afterDigest: digest } : {}), ...(object ? { recoveryRef: object.ref } : {}),
    detail: { unit: unit.unit, code: 'changed-after-publication' } })
  return { ...result, changedAfterPublication: true, observedDigest: digest, ...(object ? { objectRef: object.ref } : {}) }
}
